apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-1
  title: System 1
  description: The place to be, for great artists
spec:
  owner: group-1
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-2
  title: System 2
  description: The place to be, for great artists
spec:
  owner: group-2
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-3
  title: System 3
  description: The place to be, for great artists
spec:
  owner: group-3
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-4
  title: System 4
  description: The place to be, for great artists
spec:
  owner: group-4
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-5
  title: System 5
  description: The place to be, for great artists
spec:
  owner: group-5
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-6
  title: System 6
  description: The place to be, for great artists
spec:
  owner: group-6
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-7
  title: System 7
  description: The place to be, for great artists
spec:
  owner: group-7
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-8
  title: System 8
  description: The place to be, for great artists
spec:
  owner: group-8
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-9
  title: System 9
  description: The place to be, for great artists
spec:
  owner: group-9
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-10
  title: System 10
  description: The place to be, for great artists
spec:
  owner: group-10
---
