apiVersion: v1
kind: Namespace
metadata:
  name: rhdh-loadtests-17
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: openshift-gitops
  name: rhdh-loadtests-17
spec:
  project: rhdh-loadtests
  sources:
    - chart: redhat-developer-hub
      repoURL: https://charts.openshift.io
      targetRevision: '1.7.1'
    - repoURL: 'https://github.com/christoph-jerolimov/rhdh-loadtests.git'
      targetRevision: HEAD
      path: argocd/rhdh-17
  destination:
    name: in-cluster
    namespace: rhdh-loadtests-17
  syncPolicy:
    automated:
      enabled: true
